### ISSUE TITLE
add comparison to `pipeR` from @renkun-ken

### ISSUE THREAD

**Issue by timelyportfolio** [TobCap/demagrittr#2]
Thanks so much for your package.  Some of the speed issues with `magrittr` are discussed in this `pipeR` discussion [Differences between pipeR and magrittr](http://renkun.me/blog/2014/08/08/difference-between-magrittr-and-pipeR.html#performance).  I thought it would be interesting to also add a comparison to `pipeR` in your `Readme.md`.

@renkun-ken can probably add a lot to this discussion.

``` r
library("magrittr")
library("pipeR")
library("demagrittr")
library("microbenchmark")


expr <- quote(1:10 %>% sum %>% log %>% sin)
expr2 <- demagrittr(expr)
expr3 <- quote(1:10 %>>% sum %>>% log %>>% sin)

microbenchmark(
  "%>%" = eval(expr)
  , demagrittr = eval(expr2)
  ,"%>>%" = eval(expr3)
  ,times = 1e3
)
```

and on my machine the result

```
Unit: microseconds
       expr     min      lq       mean  median      uq      max neval cld
        %>% 124.678 132.660 144.744214 138.742 145.204 2697.298  1000   c
 demagrittr   3.041   4.181   5.078444   4.941   5.322   33.070  1000 a  
       %>>%  25.087  28.889  32.618171  30.789  33.070  188.917  1000  b 
```

**Comment by TobCap** [comment]
Thank you very much for your suggestion regarding benchmarking. The discussion you linked to is also interesting and I added those examples to README.md.

**Comment by timelyportfolio** [comment]
great, glad you found it helpful.  keep up the good work
